// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Creator struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type NewCreator struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type NewNooble struct {
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Audio       string      `json:"audio"`
	Creator     *NewCreator `json:"creator"`
}

type Nooble struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Audio       string   `json:"audio"`
	Creator     *Creator `json:"creator"`
}
